### ISSUE TITLE
Mtkclient without PC

### ISSUE THREAD

**Issue by oddsito** [topminipie/awesome-xiaomi-bootloader-unlock#1]
Is there really no way to run this tool without a PC? 
Have you tried to use it in termux?

**Comment by topminipie** [comment]
I haven't checked it out myself.

But it looks like someone did it - https://github.com/bkerler/mtkclient/issues/684

**Comment by oddsito** [comment]
Thank you for the reply, this person used mtkclient in a chroot distro with a rooted phone. It seems root access is needed in order to use it.
